import assert from "node:assert/strict";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, it } from "node:test";

import {
  MATERIALIZED_LEGACY_RUNTIME_PAIRS,
  VERSIONED_LEGACY_SOURCE_PUBLIC_PAIRS,
  findStaleFilePairs,
} from "../scripts/generated-currentness.mjs";

describe("generated currentness verifier", () => {
  it("covers only Git-custodied source/public byte pairs", () => {
    assert.deepEqual(
      VERSIONED_LEGACY_SOURCE_PUBLIC_PAIRS.map(([, generated]) => generated),
      [
        "public/data/resources.json",
        "public/journey.js",
        "public/learning-events.js",
        "public/workspace-backup.js",
        "public/assets/sufeiya-logo-header.webp",
        "public/assets/listening-writing-center.mp3",
        "public/assets/teacher-portrait/sufeiyalaoshi-homepage-640w.avif",
        "public/assets/teacher-portrait/sufeiyalaoshi-homepage-640w.webp",
        "public/assets/teacher-portrait/sufeiyalaoshi-homepage-960w.avif",
        "public/assets/teacher-portrait/sufeiyalaoshi-homepage-960w.webp",
        "public/assets/teacher-portrait/sufeiyalaoshi-homepage-1280w.avif",
        "public/assets/teacher-portrait/sufeiyalaoshi-homepage-1280w.webp",
      ],
    );
    assert.deepEqual(
      MATERIALIZED_LEGACY_RUNTIME_PAIRS.map(([, generated]) => generated),
      ["public/workspace.js", "public/script.js", "public/resources.js"],
    );
    assert.equal(
      VERSIONED_LEGACY_SOURCE_PUBLIC_PAIRS.some(([, generated]) =>
        MATERIALIZED_LEGACY_RUNTIME_PAIRS.some(([, materialized]) => materialized === generated)),
      false,
    );
  });

  it("detects changed and missing generated bytes in an isolated fixture", async () => {
    const root = await mkdtemp(join(tmpdir(), "sufeiya-currentness-test-"));
    const pairs = [["source.bin", "public/generated.bin"]] as const;
    try {
      await mkdir(join(root, "public"), { recursive: true });
      await writeFile(join(root, "source.bin"), Buffer.from([0, 1, 2]));
      await writeFile(join(root, "public/generated.bin"), Buffer.from([0, 1, 2]));
      assert.deepEqual(await findStaleFilePairs(root, pairs), []);

      await writeFile(join(root, "public/generated.bin"), Buffer.from([0, 1, 3]));
      assert.deepEqual(await findStaleFilePairs(root, pairs), ["public/generated.bin"]);
      assert.deepEqual(
        await findStaleFilePairs(root, [["source.bin", "public/missing.bin"]]),
        ["public/missing.bin"],
      );
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });
});
